[package]
name = "scl-macro"
version = "0.1.1"
edition = "2021"
description = "Some useful macros can be used in scl coding. (Highly unstable and all in Chinese!)"
homepage = "https://github.com/Steve-xmh/scl"
repository = "https://github.com/Steve-xmh/scl"
license = "LGPL-3.0-only"
readme = "README.md"
authors = ["Steve-xmh <stevexmh@qq.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "^1"
syn = "^2"

[dev-dependencies]
druid = { git = "https://github.com/linebender/druid.git", features = ["im", "serde", "raw-win-handle"] }
serde = { version = "^1", features = ["derive"] }
